### ISSUE TITLE
build-lambds support for nodejs18.x

### ISSUE THREAD

**Issue by alexmach** [LeadingEDJE/stackmanager#73]
AWS Lambdas now support nodejs18.x.

https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/

This will require https://github.com/aws/aws-lambda-builders/releases/tag/v1.23.0

**Comment by andrewdmay** [comment]
Closed by https://github.com/LeadingEDJE/stackmanager/pull/74
