### ISSUE TITLE
build-lambdas support for python 3.10

### ISSUE THREAD

**Issue by alexmach** [LeadingEDJE/stackmanager#79]
AWS Lambdas now support python3.10

https://aws.amazon.com/about-aws/whats-new/2023/04/aws-lambda-python-3-10/

This should upgrade to the latest aws-lambda-builder https://github.com/aws/aws-lambda-builders/releases/tag/v1.30.0

**Comment by andrewdmay** [comment]
Closed by https://github.com/LeadingEDJE/stackmanager/pull/80
